GKernelCI/Ghelper

kcidb/create_object.py
kcidb/get_kernel_hash.sh
kcidb/get_patch_hash.sh
kcidb/get_patches.py
kcidb/send.sh

Update the kcidb scripts

---

docker_emerge.sh

Emerge and build packages

---

build-kernel.sh
to_fileserver.sh

Revert "Multi build 1"

---

run_tests.sh
to_fileserver.sh

The goal of this PR is basicly to formalize path to artifacts and establish the same loop on copy artifacts than build (loop over defconfig)

Multi build 6a

---

gentoo_get_stage_url.sh
run_tests.sh

Use a standalone bash script for getting stage 3 URL and digest.
When GPG signature are present, this script also handle signature
verification.

Get stage3 information via a dedicated script

---

all.yaml
build-config/arm64/defconfig/artifacts/dtb
build-config/arm64/defconfig/artifacts/kernel
build-config/arm64/defconfig/defconfig
build-kernel.sh
gentoo.jinja2
run_tests.py
toolchains/x86_64/arm64/gcc/opts

This PR permits to build and boot arm64.

Build and boot arm64

---

docker_emerge.sh

This is a few changes which reduces the output of logs an fixes the docker cp

Extrasource fixes

---

run_tests.py

This patch the JOB_URL alone formated as asked by Alicef.

print JOB_URL

---

build-kernel.sh
run_tests.sh
to_fileserver.sh

Instead of building each toolchain, build only one set in BUILDER_NAME.
This PR depend on the according changes on worker.

Toolchain in buildname

---

README.md
build-kernel.sh
docker_stage3/Dockerfile
docker_stage3/builder.sh
docker_stage3/builder2.sh
docker_stage3/builder3.sh
docker_stage3/prereq.sh
docker_stage3/prereq2.sh
gen_docker_stage3.sh

This adds support for using native gentoo toolchain from stage3.

Native gentoo toolchain

---

gentoo.jinja2

WARNING: PR of Glava-tests must be merge in the same time

Split network out of kselftests

---

gentoo.jinja2

We need portage tree in rootfs for testing portage and installing
packages.

Install portage tree in rootfs

---

run_tests.py

This patch handle some error that could happen when doing devices.list()

Handle xmlrpc.Client.ProtocolError

---

all.yaml
gentoo.jinja2
run_tests.py

This PR adds real boards for gentoo tests

Add support for non qemu DUT

---

gentoo_get_stage_url.sh

GPG check do not work anymore since the signature is now done against
stage3.
So we need to download it for testing the signature.
Add some debug in the same time.

Fix GPG check of gentoo_get_stage_url.sh

---

docker_emerge.sh

If a command fail, exit status remains ok.
We need to fail is a command fail.

Handle error code in docker_emerge.sh

---

docker_emerge.sh

Building gentoo-sources curently fail with 'error: "__LIBELF_INTERNAL__" is not defined'
This is due to the missing virtual/libelf.
For handling properly dependencies, we will now use emerge directly
instead of "ebuild merge".

docker-emerge: install virtual/libelf

---

docker_emerge.sh

docker_emerge: use the date sended by GKernelCI

---

docker_emerge.sh

docker_emerge: sanitize docker container name

---

run_stabilization.sh

run_stabilization: Add stabilization script

---

docker_emerge.sh

docker_emerge: set sys-devel/bc as the package to be build

---

docker_emerge.sh

docker_emerge: add array of fileserver directory lists

---

deploy.py
run_stabilization.sh
run_tests.sh

run_stabilization: use relative path for getting kernel files

---

docker_emerge.sh
run_stabilization.sh

docker_emerge: get kernel configuration from docker image

---

run_stabilization.sh

run_stabilization: fix relpath

---

docker_emerge.sh

docker_emerge: create modules

---

docker_emerge.sh

docker_emerge: add modules in /usr/src/linux for permission issues

---

docker_emerge.sh

docker_emerge: fix pipe in docker commands

---

docker_emerge.sh

docker_emerge: add ARCH variable

---

run_stabilization.sh

run_stabilization: remove debug

---

docker_emerge.sh

with the introduction of multicontainers and docker buildx we can now use multi platform docker images

docker_emerge: add multi platform docker image

---

run_stabilization.sh

run_stabilization: update http file folder

---

check-kernelpage.py

check-kernelpage: fix getting kernel sources

---

patch-kernel.sh

patch-kernel: fix globbing

---

docker_emerge.sh

docker_emerge: update ARCH image files

---

docker_emerge.sh

docker_emerge: update x86 image path

---

docker_emerge.sh

docker_emerge: update powerpc ARCH image path

---

docker_emerge.sh

This is useful for broswer readability

docker_emerge: create txt versions of config and build log files

---

docker_emerge.sh

docker_emerge: update ARCH image file variable

---

all.yaml
toolchains/x86_64/x86/clang/opts
toolchains/x86_64/x86/clang/version
toolchains/x86_64/x86/gcc/version

Add support for testing i386

---

docker_emerge.sh

docker_emerge: try to find the kernel image with find

---

docker_emerge.sh

docker_emerge: don't exist when there is no image try instead to find it

---

do_packages_exist.sh

do_package_exist: check if "*-sources" package exist

---

gentoo_get_stage_url.sh

This reverts commit 65c563444f9d76301173147b7d296a42acef1586.

Revert "fix: use curl instead of wget"
