GKernelCI/Ghelper

kcidb/create_object.py
Simplify JSON generation to just create the structure in place instead of writing over a parsed JSON representation.
This way it's more obvious what's going in where and how.
Adding comments WRT KCIDB requirements inline.
=> create_object: Simplify JSON generation

kcidb/create_object.py, kcidb/get_patches.py, kcidb/send.sh
=> Use the linux-patches raw url as patches url

build-config/amd64/x86_64_defconfig/artifacts/kernel, build-kernel.sh, run_tests.sh, to_fileserver.sh, toolchains/x86_64/amd64/clang/opts, toolchains/x86_64/amd64/clang/version, toolchains/x86_64/amd64/gcc/version
This PR is a pre-requisites of supporting non-x86 arches:
- by permitting to use other toolchains
- by permitting to get other build artifacts
As demonstration let's add clang for x86_64
=> Multi build 7

build-kernel.sh
This fix a typo which prevent the generation of modules
=> Fix loop over modules build

all.yaml, build-config/arm/multi_v7_defconfig/artifacts/dtb, build-config/arm/multi_v7_defconfig/artifacts/kernel, build-config/arm/multi_v7_defconfig/defconfig, gentoo_get_stage_url.sh, run_tests.py, toolchains/x86_64/arm/gcc/opts
This patch adds support to build arm by using the multi_v7_defconfig.
For booting, we use the "virt" qemu machine since it is the easier to
work with. (due to virtio usage)
=> Permit to build and boot arm

build-kernel.sh, to_fileserver.sh
to_fileserver.sh was not set -e, so not exiting when cp fail.
build make errors was not atched due to tee, add pipefail to fix that.
=> Detect more shell errors

run_tests.py
Current situation made impossible to use more than one lab.
For permitting this, we need a list of LAVA labs in labs.yaml.
A hack was done before to generate it with content of lavacli.yaml.
It is time to add ability to use a native labs.yaml.
=> Use labs.yaml

gentoo_get_stage_url.sh
amd64 does not have anymore a simple latest-stage3-amd64.txt
So pick the openrc variant as defautl stage3.
=> Change default stage3 for amd64

gentoo_get_stage_url.sh
Having to choose between systemd/openrc stage3 is not amd64 only.
So let's a fallabck try to choose openrc if default stage3 does not
exists.
=> Handle new default stage3 variants

gentoo.jinja2
We need to have a working network, so let's add ip=dhcp to kernel
cmdline.
=> Add ip=dhcp to qemu kernel cmdline

docker_emerge.sh
Official gentoo stage3 images removed the -ARCH from the name.
So now we need to use just "gentoo/stage3just"
=> Gentoo docker images was renamed

docker_emerge.sh
We need to enable symlink use flag for having the /usr/src/linux symlink
created.
=> Enable symlink use flag

docker_emerge.sh
We cannot use emerge as portage tree is not the right place
=> Install gentoolkit with ebuild

docker_emerge.sh
Add PYTHON_TARGETS as needed by gentoolkit.
Add also the symlink to portage tree and some comments.
Prevent also to grab live ebuild for gentoolkit
Signed-off-by: Corentin LABBE <clabbe@baylibre.com>
=> gentoolkit need PYTHON_TARGETS

docker_emerge.sh
The "$*" parameters shoud not be passed to make since it fails the
build.
=> docker-emerge: remove useless parameters

gentoo.jinja2
TODO: As kselftest takes to much time we should follow
linaro kselftest and enable only the needed tests
instead of skipping results.
Also make kselftest optional.
For now removing kselftest.
=> Kselftest should be optional

check-kernelpage.py
I found from the recent GKernelCI builds that one source of failures is the directory structure here:
http://distfiles.gentoo.org/distfiles/
While I opened this in a browser, I found that they have a new requirement which is that each file you want to download must include in the url a two digit blake 2b hash must be included. This change adds that hash.
failing build: https://gkernelci.gentoo.org/#/builders/12/builds/197/steps/5/logs/stdio
=> fix: adjust kernel url for gentoo dist source

deploy.py, gentoo_get_stage_url.sh
this patch comes with a couple minor fixes. One of which is that the urls referenced in
http://ftp.free.fr/mirrors/ftp.gentoo.org/releases/x86_64/autobuilds
now require using amd64 instead of x86_64. As for the other parameters, like larch and qarch, I did not think it was necessary to change to use amd64 because qemu still references their x86_64 binaries as qemu-system-x86_64 , and linux in general still uses the x86_64 wording.
As for the other change, I noticed that the following url:
http://ftp.free.fr/mirrors/ftp.gentoo.org/releases/amd64/autobuilds/latest-stage3-amd64-openrc.txt
outputs the following:
> -----BEGIN PGP SIGNED MESSAGE-----
> Hash: SHA256
>
> # Latest as of Mon, 21 Apr 2025 22:00:01 +0000
> # ts=1745272801
> 20250420T121009Z/stage3-amd64-openrc-20250420T121009Z.tar.xz …
=> fix: use amd64 for references to x86_64 since it's used in urls

all.yaml, deploy.py
In my previous commit
54e7e91da42b9ad8723173fd8547b8485666a89d
I changed a few references from x86_64 to amd64, however, I missed one that needs to refer to amd64. The reason this needs to be amd64 is because of the checks in deploy.py
if device_larch != larch:
continue
if device["arch"] != arch:
continue
defined above:
larch = x86_64
arch = amd64
from all.yaml:
device["arch"] was x86_64, therefore this check device["arch"] != arch
would be True and therefore skipped.
And larch was x86_64, which means device_larch != larch was True.
=> fix: change arch to amd64 instead of x86_64

run_tests.sh
I was having trouble at one point because I was defining STORAGE_SERVER but this env var was getting overwritten by the script run_tests.sh
=> fix: do not hard-code STORAGE_SERVER if defined

deploy.py
I was investigating the failed run today
https://gkernelci.gentoo.org/#/builders/12/builds/198
And was pretty confused from the limited output:
```
BOOT: /var/www/fileserver//6.1_amd64_gcc/amd64/198//x86_64_defconfig/gcc
INFO: arch is amd64, Linux arch is x86_64, QEMU arch is x86_64
ERROR: there is some fail
```
Based on this, I determined that deploy.py returned a status code 1 with no error message. So I searched everywhere in deploy.py for a `system.exit(1)` call with no print statement above it and added a print statement above it. That way, the next build we get, we know what line it failed on.
=> fix: add extra debug statements
